---
after_script:
- rake travis:after -t
before_script:
- gem install rake-compiler -v '>= 0.4.1'
- gem install hoe-travis --no-rdoc --no-ri
- rake travis:before -t
language: ruby
notifications:
  email:
script: rake travis
matrix:
  include:
    - os: linux
      rvm: 2.1.10
    - os: linux
      rvm: 2.2.5
    - os: linux
      rvm: 2.3.1
    - os: linux
      rvm: 2.4.0
      env:
        - RUBYOPT="--enable-frozen-string-literal --debug=frozen-string-literal"
